cats/urls.py
from django.conf.urls import patterns, url

from cats import views

urlpatterns = patterns('',
    # The main page
    url(r'^$',
        views.index,
        name='index'),

    # Submission form page
    url(r'^submit/$',
        views.submit,
        name='submit'),

    # Cat data page shows the photo the user has submitted
    url(r'^display/(\w+)-(?P<cat_id>\d+)/data/(?P<cat_data_id>\d+)/$',
        views.display_cat_data,
        name='display_cat_data'),

    # Cat page shows all submissions for one cat
    url(r'^display/(\w+)-(?P<cat_id>\d+)/$',
        views.display_cat,
        name='display_cat'),

    # AJAX load of average cuteness after user votes
    url(r'^vote/(?P<cat_data_id>\d+)/$',
        views.vote,
        name='vote_catdata'),

    # Search page
    url(r'^search/search/$',
        views.search,
        name='search'),
)

cute/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cats/', include('cats.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cats/models.py
from django.db import models


# Each cat has one database entry (although users can upload multiple photos of their cat)
class Cat (models.Model):
    name = models.CharField(max_length=150)
    created = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.name

# This is the model for individual cat photo submissions
class CatData(models.Model):
    cat = models.ForeignKey(Cat, related_name="data")
    photo = models.ImageField(upload_to='catimages/')
    story = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

# Database items affected by a user's cuteness vote
class Vote(models.Model):
    cat_data = models.OneToOneField(CatData, related_name='vote')
    cuteness_sum = models.PositiveIntegerField(default=0)
    num_votes = models.IntegerField(default=0)

    # Calculates average cuteness, which is displayed after a user votes
    @property
    def avg_cuteness(self):
        ave = self.cuteness_sum / float(self.num_votes)
        return "%.2f" % ave

cats/forms.py
from django import forms
from cats.models import Cat, CatData, Vote


# Users submit cat photos using this form
class CatDataForm(forms.Form):
    catname = forms.CharField(max_length=150, required=True)
    photo = forms.FileField(required=True)
    story = forms.CharField()
    
    def save(self):
        cat, is_newcat = Cat.objects.get_or_create(name=self.cleaned_data['catname'])
        catdata = CatData(cat=cat, story=self.cleaned_data['story'])
        catdata.save()
        catdata.photo.save('%s.jpg' % catdata.id, self.cleaned_data['photo'])
        catdata.save()
        return (cat, catdata)
        
# Users vote with this form
class VoteForm(forms.Form):
    vote = forms.IntegerField()

# Users search for a cat with this form
class SearchForm(forms.Form):
    namesearch = forms.CharField(max_length=150)
    idsearch = forms.IntegerField()
 

cats/views.py
import json

from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from cats.models import Cat, CatData, Vote
from cats.forms import CatDataForm, VoteForm

# Displays a random cat for the user to vote on
def index(request):
    random_catdata = CatData.objects.order_by("?")[0]
    return render(request,
                'cats/index.html',
                {'random_catdata': random_catdata})

# Adds data submitted by user to database
def submit(request):
    if request.method == 'POST':
        form = CatDataForm(request.POST, request.FILES)
        if form.is_valid():
            cat, cat_data = form.save()
            return HttpResponseRedirect(reverse('display_cat_data',
                                                args=(cat.name, cat.id, cat_data.id)))
    else:
        form = CatDataForm()
    return render(request,
                  'cats/submit.html',
                  {'form' : form}
    )

# Loads all submissions for a single cat
def display_cat(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    return render(request,
                  'cats/display.html',
                  {'cat': cat})

# Shows a single photo submission
def display_cat_data(request, cat_id, cat_data_id):
    cat = Cat.objects.get(id=cat_id)
    cat_data = CatData.objects.get(cat=cat, id=cat_data_id)
    return render(request,
                  'cats/display_data.html',
                  {
                    'cat': cat,
                    'cat_data': cat_data
                  })

# Submits user vote and calculations based on it to database; AJAX loads the average cuteness
def vote(request, cat_data_id):
    catdata = CatData.objects.get(id=cat_data_id)
    if request.method == 'POST':
        form = VoteForm(request.POST)
        if form.is_valid():
            if not hasattr(catdata, 'vote'):
                Vote.objects.create(cat_data=catdata)
            cat_vote = catdata.vote
            cat_vote.cuteness_sum += form.cleaned_data.get('vote')
            cat_vote.num_votes += 1
            cat_vote.save()
            response_data = {'average': cat_vote.avg_cuteness}
            return HttpResponse(json.dumps(response_data), content_type="application/json")

# Allows user to search for cat by its name or ID
def search(request):
    # ID search will redirect to Display Cat page for that cat
    if 'idsearch' in request.GET:
        idsearch = request.GET['idsearch']
        cat = Cat.objects.get(id=idsearch)
        return HttpResponseRedirect(reverse('display_cat',
                                            args=(cat.name, cat.id)))
    # Name search will AJAX load most recent photo for each cat with that name
    elif 'namesearch' in request.GET:
        namesearch = request.GET['namesearch']
        cats = Cat.objects.filter(name__iexact=namesearch)
        response_data = []
        for cat in cats:
            catdata = CatData.objects.filter(cat=cat).latest('created')
            response_data.append({
                'photo_url': catdata.photo.url,
                'url': reverse('display_cat', args=(cat.name, cat.id)),
                'id': cat.id,
                'name': cat.name
            })
        return HttpResponse(json.dumps(response_data), content_type="application/json")
        
    return render(request,
                  'cats/search.html',
                  )

cats/templates/cats/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<html>
<head>
    <title>Cute or Really Cute?</title>
    {% load staticfiles %}
    <link href="{% static 'cats/slider/css/overcast/jquery-ui-1.10.4.custom.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Alike' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Gudea' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Asap' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Annie+Use+Your+Telescope' rel='stylesheet' type='text/css'>
    <script src="{% static 'cats/slider/js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'cats/slider/js/jquery-ui-1.10.4.custom.js' %}"></script>
    
   <script>
        
        // Adds a random border to each image, without repeating borders until it uses them all.

        var borders = [];
        var numBorders = 8;
        function makeUniqueRandom() {
            if (!borders.length) {
                for (var i=0; i < numBorders; i++) {
                    borders.push(i);
                }
            }
            var index = Math.floor(Math.random() * borders.length);
            var val = borders[index];
            
            borders.splice(index, 1);
            
            return val;
        }
        
        $(document).ready(function() {
            $('img').each(function(i) {
                $(this).addClass('border' + (makeUniqueRandom() + 1));
            });
        });
    
        
        
    </script>
    
    {% block head %}
    
       
    {% endblock head %}
    
</head>

<body>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'cats/cutecats.css' %}" />
    <h1><a href="{% url "index" %}" class="cute">Cute <span>or<span> Really Cute</span></span></a></h1>
    
    {% block content %}
    <div class="center"></div>
    {% endblock %}
</body>
</html>

cats/templates/cats/display.html
<!-- Corresponds to "Display Cat" url. Displays all photos with ratings for one cat -->

    {% extends "base.html" %}
    {% block content %}

    <br>
    <p>Cat: {{ cat.name }}
    <br>Cat ID: {{ cat.id }}</p>
    
    <p>{% for cat_data in cat.data.all %}
        <table id="catdisplay">
        <!-- Alternates display so cat photo is to the right or left of cuteness rating -->
            {% if forloop.counter|divisibleby:"2" %}
                <tr>
                    <td class="catpiccuteness" id="rotater">
                        Average <br>
                        Cuteness: <br>
                        {{ cat_data.vote.avg_cuteness }}
                    </td>
                    <td class="catpicr">
                        <a href="{% url 'display_cat_data' cat.name cat.id cat_data.id %}">
                        <img src="{{ cat_data.photo.url }}" style="max-height:300px; width:auto">
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td class="catpicl">
                        <a href="{% url 'display_cat_data' cat.name cat.id cat_data.id %}">
                        <img src="{{ cat_data.photo.url }}" style="max-height:300px; width:auto">
                        </a>
                    </td>
                    <td class="catpiccuteness" id="rotatel">
                        Average <br>
                        Cuteness: <br>
                        {{ cat_data.vote.avg_cuteness }}
                    </td>
                </tr>
            {% endif %}
        </table>
    {% endfor %} </p>
    
    {% endblock %}

cats/templates/cats/display_data.html
<!-- Corresponds to "display cat data" url. Shows one photo submission. -->

{% extends "base.html" %}

    {% block content %}

        <p>Cat: <a href="{% url "display_cat" cat.name cat.id %}">{{ cat.name }}</a></p>
        <img src="{{ cat_data.photo.url }}" style="max-height:500px; width:auto">
        <p>Story: {{ cat_data.story }}<br clear="all"></p>
    
    {% endblock %}

cats/templates/cats/index.html
<!-- Main page. Displays random cat photo with a slider that allows users to vote. -->

{% extends "base.html" %}
{% block content %}
    <br>
    <div class="container">
        
        <p>{{ random_catdata.story }}</p>
           
        <img src='{{ random_catdata.photo.url }}' style="max-height: 500px; width: auto">
            
        <br>
        <br>
        <br>

        <div id="sliderbox">
            <p style="text-align:left; padding-left:150px">How cute is {{ random_catdata.cat }}?
        
        <br>
        
            <div id="slider"></div>
            <button id="vote" form="VoteForm" type="submit">Vote</button>
            <br>
            <br>


        <!-- Custom CSS for the voting slider -->
        <style type="text/css">
            .ui-slider-horizontal .ui-state-default {
              background: white url(/static/cats/4567.gif) no-repeat scroll 50% 50%;
              z-index: -1;
            }

            .ui-slider-tick-mark{
                display:inline-block;
                width:4px;
                background: #aaaaaa;
                height:25px;
                position:absolute;
                top: -7px;
                margin-left: -1px;
                z-index: -1;
            }

            #slider {
                margin-left: auto;
                margin-right: auto;
                width: 400px;
            }

            .ui-corner-all {
              border-radius:3px;
            }

            .ui-slider-number {
                color: black;
                display:inline-block;
                height:25px;
                position:absolute;
                top: 20px;
            }

            .ui-slider-horizontal .ui-slider-handle{
              top: -.9em;
              margin-left: -.9em;
            }

            .ui-slider .ui-slider-handle {
              position: absolute;
              z-index: 2;
              width: 32px;
              height: 32px;
              cursor: default;
            }

            .ui-widget-content {
              border: 2px dotted #aaaaaa;
              height: 10px;
            }

            .ui-widget {
              font-family: "Lucida Bright", serif;
            }
            </style>

          <script>
            // This creates a slider that allows the user to vote from 1-10
            function setSliderTicks(){
                var $slider =  $('#slider');
                var max =  $slider.slider("option", "max");
                var min = $slider.slider('option', 'min');
                var spacing =  99.6 / (max - min);
            
                $slider.find('.ui-slider-tick-mark').remove();
                for (var i = 0; i < max ; i++) {
                    var leftVal = (spacing * i) + '%';
                    $('<span class="ui-slider-tick-mark"></span>').css('left', leftVal).appendTo($slider);
                    var sliderNumber = $('<span class="ui-slider-number">'+(i+1)+'</span>').appendTo($slider);
                    sliderNumber.css('left', leftVal);
                    console.log(leftVal);
                    sliderNumber.css('left',
                                     sliderNumber.css('left').replace('px', '') - (sliderNumber.width()/2));
                 }
            }

            // This changes the slider cat image depending on how the user votes
            var sliderImages = ['/static/cats/123.gif',
                                '/static/cats/4567.gif',
                                '/static/cats/8910.gif'];
            $(function() {
                $("#slider" ).slider({
                    value:5,
                    min: 1,
                    max: 10,
                    step: 1,
                    slide: function( event, ui ) {
                        sliderImageIdx = 0
                        if (ui.value <= 3) {
                            sliderImageIdx = 0
                        }
                        else if (ui.value >= 8) {
                            sliderImageIdx = 2;
                        }
                        else {
                            sliderImageIdx = 1;
                        };	
                        //var sliderImageIdx = ui.value % 3;
                        $(this).find('.ui-slider-handle').css('background-image',
                                                              'url('+sliderImages[sliderImageIdx]+')');
                    }
                });
                setSliderTicks();

                // Submits user vote and displays average cuteness of cat
                $("#vote").click(function() {
                    $.ajax("{% url 'vote_catdata' random_catdata.id %}", {
                        data: {vote: $('#slider').slider('value')},
                        type: 'POST',
                        success: function(data) {
                                $('#vote').replaceWith('<button id="next">Next</button>');
                                $('#beforeave').remove();
                                $('#average').append("Average Cuteness: " + data.average);
                        }
                    });
                });
                $("#sliderbox").on('click', '#next', function() {
                    location.reload(true);
                });
            });
          </script>
        </div>

        <br>
        <br>

        <div id="average"></div>

            <div id="beforeave" style="font-family:'Alike', serif; font-size:x-large">
                <br>
            </div>
        <br>
        <br>
        <br>
        <br>
      
        <a id="searchkitty" href="{% url 'search' %}">
            <button class="ssbuttons">
                Search the Cats
            </button>
        </a>
        <a id="submitkitty" href="{% url 'submit' %}">
            <button class="ssbuttons">
                Submit your kitty!
            </button>
        </a>
    </div>
    
    <br>
    <br>   
   
    
{% endblock %}

cats/templates/cats/search.html
<!-- Search page that allows user to find a cat by its name or ID -->

{% extends "base.html" %}
{% block head %}
    
<script>
    // If user searches by name, page will load most recent photo of each cat by that name
    var template = {};
    $(document).ready(function() {
        template['searchUrl'] = '{% url "search" %}';
        $("#ns_form").submit(function(event) {
            $.ajax(template['searchUrl'], {
                data: {'namesearch': $('#ns_text').val()},
                type: 'GET',
                error: function() {
                    $('#results').append("There are no cats by that name.");
                },
                success: function(data) {
                    $.each(data, function(idx, el) {
                        $('#results').append('<a href="' + el.url + '">' + '<img style="max-height:300px; width:auto" src='
                                             + el.photo_url + '>' + '</a>');
                    });
                    }
                });
            event.preventDefault();
         });
    });
</script>    
{% endblock head %}


{% block content %}


<div class="container">   
	
    <br>
    <br>
	
    <div id="search">
        <h2> Search for a cat you have submitted: </h2>
	
        <form id="ns_form" method="get" action=""> 
            <p>Cat Name: <input type="text" id="ns_text" />
            <input id="namesearch" type="submit" value="search" /></p>
        </form>
		
        <form method="get" action="">
            <p>Cat ID: <input type="text" name="idsearch" />
            <input type="submit" value="search" /></p>
        </form> 
        
    </div>
    
    <br>
    <br>
	
    <div id="results">
        
        
    </div>
	
</div>
	
{% endblock %}

cats/templates/cats/submit.html
<!-- Submission form to upload a new cat photo -->

{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div id="submit">
        <br>
        <br>
        {{ form.errors }}
        <form action="{% url "submit" %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            <p>
                {{ form.catname.errors }}
                <label for="id_catname">Name of Your Cat:</label>
                {{ form.catname }}
            </p>
            <p>
                <label for="id_photo">Photo:</label>
                {{ form.photo }}
            </p>
            <p>
                <label for="id_story">Cute story:</label>
                {{ form.story }}
                <br>
                <br>
                <input type="submit" value="Submit" />
            </p>
        </form>
        </div>
    </div>
    
{% endblock %}